/*
 * Copyright 2014 Alessandro Falappa <alex.falappa@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.xml.namespace.QName;

import org.apache.axis2.AxisFault;
import org.apache.axis2.addressing.EndpointReference;
import org.apache.xmlbeans.XmlCursor;
import org.apache.xmlbeans.XmlObject;
import org.apache.xmlbeans.XmlOptions;

import data.CatalogueDefinition;
import gov.nasa.worldwind.BasicModel;
import gov.nasa.worldwind.event.RenderingExceptionListener;
import gov.nasa.worldwind.exception.WWAbsentRequirementException;
import gov.nasa.worldwind.geom.LatLon;
import gov.nasa.worldwind.layers.Layer;
import gov.nasa.worldwind.layers.LayerList;
import gov.nasa.worldwind.layers.placename.PlaceNameLayer;
import gov.nasa.worldwindx.examples.util.StatusLayer;
import gui.dialogs.CatDefinitionDialog;
import gui.wwind.AOILayer;
import gui.wwind.FootprintsLayer;
import gui.wwind.MOILayer;
import main.App;
import main.HmaGetRecordsBuilder;
import net.opengis.www.cat.csw._2_0_2.GetRecordsDocument;
import net.opengis.www.cat.csw._2_0_2.GetRecordsResponseDocument;
import net.opengis.www.cat.wrs._1_0.CatalogueStub;

/**
 * HCC main window.
 * <p>
 * @author Alessandro Falappa <alex.falappa@gmail.com>
 */
public class MainWindow extends javax.swing.JFrame {

    public FootprintsLayer footprints;
    public AOILayer aois;
    public MOILayer mois;
    private final DefaultComboBoxModel<CatalogueDefinition> dcmCatalogues = new DefaultComboBoxModel<>();
    private final HmaGetRecordsBuilder builder = new HmaGetRecordsBuilder();
    private CatalogueStub stub = null;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setupWorldWind();
        try {
            stub = new CatalogueStub();
        } catch (AxisFault ex) {
            //ignored
        }
    }

    public CatalogueDefinition getCurrentCatalogue() {
        return (CatalogueDefinition) cbCatalogues.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pQueryParams = new javax.swing.JPanel();
        pCollections = new gui.panels.CollectionsPanel();
        pTime = new gui.panels.TimeWindowPanel();
        pGeo = new gui.panels.GeoAreaPanel();
        pSearchButons = new gui.panels.SearchButtonsPanel();
        pGlobe = new javax.swing.JPanel();
        wwCanvas = new gov.nasa.worldwind.awt.WorldWindowGLCanvas();
        pToolBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbCatalogues = new javax.swing.JComboBox();
        bAddCat = new javax.swing.JButton();
        bDelCat = new javax.swing.JButton();
        lMexs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMA Catalogue Client");

        pQueryParams.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 6, 0, 0));
        pQueryParams.setLayout(new javax.swing.BoxLayout(pQueryParams, javax.swing.BoxLayout.PAGE_AXIS));
        pQueryParams.add(pCollections);
        pQueryParams.add(pTime);
        pQueryParams.add(pGeo);
        pQueryParams.add(pSearchButons);

        getContentPane().add(pQueryParams, java.awt.BorderLayout.WEST);

        pGlobe.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 6, 6));
        pGlobe.setLayout(new java.awt.BorderLayout());
        pGlobe.add(wwCanvas, java.awt.BorderLayout.CENTER);

        getContentPane().add(pGlobe, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Catalogue");

        cbCatalogues.setModel(dcmCatalogues);

        bAddCat.setText("+");
        bAddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddCatActionPerformed(evt);
            }
        });

        bDelCat.setText("-");
        bDelCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelCatActionPerformed(evt);
            }
        });

        lMexs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pToolBarLayout = new javax.swing.GroupLayout(pToolBar);
        pToolBar.setLayout(pToolBarLayout);
        pToolBarLayout.setHorizontalGroup(
            pToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCatalogues, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAddCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDelCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMexs, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pToolBarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bAddCat, bDelCat});

        pToolBarLayout.setVerticalGroup(
            pToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pToolBarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddCat)
                    .addComponent(cbCatalogues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMexs)
                    .addComponent(jLabel1)
                    .addComponent(bDelCat))
                .addGap(6, 6, 6))
        );

        getContentPane().add(pToolBar, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddCatActionPerformed
        CatDefinitionDialog d = new CatDefinitionDialog(this);
        d.setLocationRelativeTo(this);
        d.setVisible(true);
        if (d.isOkPressed()) {
            cbCatalogues.addItem(d.getDefinedCatalogue());
        }
    }//GEN-LAST:event_bAddCatActionPerformed

    private void bDelCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelCatActionPerformed
        if (cbCatalogues.getSelectedIndex() >= 0) {
            dcmCatalogues.removeElementAt(cbCatalogues.getSelectedIndex());
        }
    }//GEN-LAST:event_bDelCatActionPerformed

    private void setupWorldWind() {
        BasicModel model = new BasicModel();
        wwCanvas.setModel(model);
//        highlightController = new HighlightController(wwCanvas, SelectEvent.ROLLOVER);
//        ttController = new ToolTipController(wwCanvas);
        // Register a rendering exception listener
        wwCanvas.addRenderingExceptionListener(new RenderingExceptionListener() {
            @Override
            public void exceptionThrown(Throwable t) {
                if (t instanceof WWAbsentRequirementException) {
                    StringBuilder message = new StringBuilder(
                            "Computer does not meet minimum graphics requirements.\n");
                    message.append("Please install up-to-date graphics driver and try again.\n");
                    message.append("Reason: ").append(t.getMessage());
                    message.append("\nThis program will end when you press OK.");
                    JOptionPane.showMessageDialog(MainWindow.this, message, "Unable to Start Program", JOptionPane.ERROR_MESSAGE);
                    System.exit(-1);
                } else {
                    System.err.println("WorldWind library rendering problem!");
                    t.printStackTrace(System.err);
                }
            }
        });
        // add a StatusLayer
        StatusLayer slayer = new StatusLayer();
        slayer.setEventSource(wwCanvas);
        slayer.setDefaultFont(bAddCat.getFont());
        wwCanvas.getModel().getLayers().add(slayer);
        // get position of place names layer
        LayerList layers = model.getLayers();
        int position = 0;
        for (Layer l : layers) {
            if (l instanceof PlaceNameLayer) {
                position = layers.indexOf(l);
                break;
            }
        }
        // create footprints and AOI layers and add them before the place names
        footprints = new FootprintsLayer();
        layers.add(position, footprints);
        aois = new AOILayer();
        layers.add(position, aois);
        mois = new MOILayer();
        layers.add(position, mois);
        // link panels to globe
        pGeo.linkTo(wwCanvas, aois, mois);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddCat;
    private javax.swing.JButton bDelCat;
    private javax.swing.JComboBox cbCatalogues;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lMexs;
    private gui.panels.CollectionsPanel pCollections;
    private gui.panels.GeoAreaPanel pGeo;
    private javax.swing.JPanel pGlobe;
    private javax.swing.JPanel pQueryParams;
    private gui.panels.SearchButtonsPanel pSearchButons;
    private gui.panels.TimeWindowPanel pTime;
    private javax.swing.JPanel pToolBar;
    public gov.nasa.worldwind.awt.WorldWindowGLCanvas wwCanvas;
    // End of variables declaration//GEN-END:variables

    public void execHits() {
        if (!pCollections.collectionSelected()) {
            JOptionPane.showMessageDialog(this, "At least one collection must be selected", "Submission error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        pSearchButons.enableButtons(false);
        builder.reset();
        startWorker(false);
    }

    public void execResults() {
        if (!pCollections.collectionSelected()) {
            JOptionPane.showMessageDialog(this, "At least one collection must be selected", "Submission error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        pSearchButons.enableButtons(false);
        builder.reset();
        startWorker(true);
    }

    GetRecordsDocument buildReq(boolean isResults) {
        builder.setDetailSummary();
        if (isResults) {
            builder.setResults();
        } else {
            builder.setHits();
        }
        builder.setMaxRecords(pSearchButons.getMaxRecs());
        builder.setStartPosition(pSearchButons.getStartPos());
        //add collections
        String[] colls = pCollections.getSelectedCollections();
        if (colls != null) {
            if (colls.length == 1) {
                builder.addCollection(colls[0]);
            } else {
                builder.addCollections(colls);
            }
        }
        // add time constraints
        if (pTime.constraintsEnabled()) {
            switch (pTime.getOperator()) {
                case 0:
                    builder.addTemporalContained(pTime.getT1(), pTime.getT2());
                    break;
                case 1:
                    builder.addTemporalOverlaps(pTime.getT1(), pTime.getT2());
                    break;
                case 2:
                    builder.addTemporalAfter(pTime.getT1());
                    break;
                case 3:
                    builder.addTemporalBefore(pTime.getT1());
                    break;
            }
        }
        // add spatial constraints
        if (pGeo.constraintsEnabled()) {
            switch (pGeo.getOperator()) {
                case 0:
                    switch (pGeo.getPrimitive()) {
                        case 0:
                            builder.addSpatialOverlapsRange(pGeo.getRangeLatMin(), pGeo.getRangeLatMax(), pGeo.getRangeLonMin(), pGeo.getRangeLonMax());
                            break;
                        case 1:
                            builder.addSpatialOverlapsPolygon(pGeo.getPolygonCoords());
                            break;
                        case 2:
                            builder.addSpatialOverlapsCircle(pGeo.getCircleCenterLat(), pGeo.getCircleCenterLon(), pGeo.getCircleRadius());
                            break;
                        case 3:
                            builder.addSpatialOverlapsPolyline(pGeo.getPolylineCoords());
                            break;
                        case 4:
                            builder.addSpatialOverlapsPoint(WIDTH, WIDTH);
                            break;
                    }
                    break;
                case 1:
                    switch (pGeo.getPrimitive()) {
                        case 0:
                            builder.addSpatialContainsRange(pGeo.getRangeLatMin(), pGeo.getRangeLatMax(), pGeo.getRangeLonMin(), pGeo.getRangeLonMax());
                            break;
                        case 1:
                            builder.addSpatialContainsPolygon(pGeo.getPolygonCoords());
                            break;
                        case 2:
                            builder.addSpatialContainsCircle(pGeo.getCircleCenterLat(), pGeo.getCircleCenterLon(), pGeo.getCircleRadius());
                            break;
                        case 3:
                            builder.addSpatialContainsPolyline(pGeo.getPolylineCoords());
                            break;
                        case 4:
                            builder.addSpatialContainsPoint(pGeo.getPointLat(), pGeo.getPointLon());
                            break;
                    }
                    break;
                case 2:
                    switch (pGeo.getPrimitive()) {
                        case 0:
                            builder.addSpatialIntersectsRange(pGeo.getRangeLatMin(), pGeo.getRangeLatMax(), pGeo.getRangeLonMin(), pGeo.getRangeLonMax());
                            break;
                        case 1:
                            builder.addSpatialIntersectsPolygon(pGeo.getPolygonCoords());
                            break;
                        case 2:
                            builder.addSpatialIntersectsCircle(pGeo.getCircleCenterLat(), pGeo.getCircleCenterLon(), pGeo.getCircleRadius());
                            break;
                        case 3:
                            builder.addSpatialIntersectsPolyline(pGeo.getPolylineCoords());
                            break;
                        case 4:
                            builder.addSpatialIntersectsPoint(pGeo.getPointLat(), pGeo.getPointLon());
                            break;
                    }
                    break;
                case 3:
                    switch (pGeo.getPrimitive()) {
                        case 0:
                            builder.addSpatialIsContainedRange(pGeo.getRangeLatMin(), pGeo.getRangeLatMax(), pGeo.getRangeLonMin(), pGeo.getRangeLonMax());
                            break;
                        case 1:
                            builder.addSpatialIsContainedPolygon(pGeo.getPolygonCoords());
                            break;
                        case 2:
                            builder.addSpatialIsContainedCircle(pGeo.getCircleCenterLat(), pGeo.getCircleCenterLon(), pGeo.getCircleRadius());
                            break;
                        case 3:
                            builder.addSpatialIsContainedPolyline(pGeo.getPolylineCoords());
                            break;
                        case 4:
                            builder.addSpatialIsContainedPoint(pGeo.getPointLat(), pGeo.getPointLon());
                            break;
                    }
                    break;
            }
        }
        final GetRecordsDocument request = builder.getRequest();
        System.out.println("********** Request ******************");
        System.out.println(request.xmlText(new XmlOptions().setSavePrettyPrint()));
        return request;
    }

    int processResponse(GetRecordsResponseDocument resp) {
        if (resp == null) {
            return 500;
        }
        System.out.println("********** Response ******************");
        System.out.println(resp.xmlText(new XmlOptions().setSavePrettyPrint()));
        // extract footprints
        XmlObject[] res = resp.selectPath("declare namespace rim='urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0' .//rim:RegistryPackage");
        if (res.length > 0) {
            App.frame.footprints.removeAllRenderables();
        }
        for (XmlObject xo : res) {
            // extract pid
            XmlCursor xc = xo.newCursor();
            String pid = xc.getAttributeText(new QName("id"));
            xc.dispose();
            // extract footprint coordinates
            XmlObject[] xpos = xo.selectPath("declare namespace gml='http://www.opengis.net/gml' .//gml:posList");
            if (xpos.length == 0) {
                continue;
            }
            xc = xpos[0].newCursor();
            String[] coords = xc.getTextValue().split("\\s");
            xc.dispose();
            List<LatLon> geopoints = new ArrayList<LatLon>();
            for (int i = 0; i < coords.length; i += 2) {
                double lat = Double.valueOf(coords[i]);
                double lon = Double.valueOf(coords[i + 1]);
                geopoints.add(LatLon.fromDegrees(lat, lon));
            }
            App.frame.footprints.addSurfPoly(geopoints, pid);
        }
        return res.length;
    }

    void enableSearchButtons(boolean enabled) {
        pSearchButons.enableButtons(enabled);
    }

    private void startWorker(boolean isResults) {
        final CatalogueDefinition currCatDef = getCurrentCatalogue();
        if (currCatDef.isSoapV12()) {
            //TODO set soap 1.2 in stub
        }
        stub._getServiceClient().setTargetEPR(new EndpointReference(currCatDef.getEndpoint()));
        GetRecordsWorker grw = new GetRecordsWorker(this, stub, isResults);
        grw.execute();
    }
}
