/*
 * Copyright (C) 2012-2014 Telespazio S.p.A. - A Finmeccanica / Thales Company
 * All rights reserved.
 *
 * This document discloses subject matter in which Telespazio S.p.A. has
 * proprietary rights. Recipient of the document shall not duplicate, use or
 * disclose in whole or in part, information contained herein except for or on
 * behalf of Telespazio S.p.A. to fulfill the purpose for which the document was
 * delivered to him.
 */
package net.falappa.wwind.widgets;

import java.util.prefs.Preferences;

/**
 * Modeless dialog grouping a {@link DynamicCartoVisibilityPanel}, a {@link VisualAidsVisibilityPanel} and a
 * {@link SurfShapeLayersVisibilityPanel} together.
 *
 * @author Fabrizio Fabri
 * @author Alessandro Falappa
 */
public class DynamicLayerSettingsDialog extends javax.swing.JDialog {

    /**
     * Creates a new dialog.
     *
     * @param parent parent frame
     */
    public DynamicLayerSettingsDialog(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
    }

    /**
     * Creates a new dialog.
     *
     * @param parent parent dialog
     */
    public DynamicLayerSettingsDialog(java.awt.Dialog parent) {
        super(parent, false);
        initComponents();
    }

    /**
     * Link the dialog to the given WWindPanel.
     *
     * @param wwp the panel to link to
     */
    public void linkTo(WWindPanel wwp) {
        pSurfShpLayers.linkTo(wwp);
        pBaseVmap.linkTo(wwp);
        pVisAids.linkTo(wwp);
    }

    public void loadPrefs(Preferences viewPrefs) {
        pBaseVmap.loadPrefs(viewPrefs);
        pVisAids.loadPrefs(viewPrefs);
    }

    public void storePrefs(Preferences viewPrefs) {
        pBaseVmap.storePrefs(viewPrefs);
        pVisAids.storePrefs(viewPrefs);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pSurfShpLayers = new net.falappa.wwind.widgets.SurfShapeLayersVisibilityPanel();
        pVisAids = new net.falappa.wwind.widgets.VisualAidsVisibilityPanel();
        pBaseVmap = new net.falappa.wwind.widgets.DynamicCartoVisibilityPanel();

        setTitle("Layer settings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pSurfShpLayers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pVisAids, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pBaseVmap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSurfShpLayers, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pVisAids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pBaseVmap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.falappa.wwind.widgets.DynamicCartoVisibilityPanel pBaseVmap;
    private net.falappa.wwind.widgets.SurfShapeLayersVisibilityPanel pSurfShpLayers;
    private net.falappa.wwind.widgets.VisualAidsVisibilityPanel pVisAids;
    // End of variables declaration//GEN-END:variables
}
