package net.falappa.wwind.widgets;

import java.util.prefs.Preferences;

/**
 * Modeless dialog grouping a {@link BaseCartoVisibilityPanel}, a {@link VisualAidsVisibilityPanel} and a
 * {@link SurfShapeLayersVisibilityPanel} together.
 *
 * @author Fabrizio Fabri
 * @author Alessandro Falappa
 */
public class LayerSettingsDialog extends javax.swing.JDialog {

    /**
     * Creates a new dialog.
     *
     * @param parent parent frame
     */
    public LayerSettingsDialog(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
    }

    /**
     * Creates a new dialog.
     *
     * @param parent parent dialog
     */
    public LayerSettingsDialog(java.awt.Dialog parent) {
        super(parent, false);
        initComponents();
    }

    /**
     * Link the dialog to the given WWindPanel.
     *
     * @param wwp the panel to link to
     */
    public void linkTo(WWindPanel wwp) {
        pSurfShpLayers.linkTo(wwp);
        pBaseCarto.linkTo(wwp);
        pVisAids.linkTo(wwp);
    }

    public void loadPrefs(Preferences viewPrefs) {
        pBaseCarto.loadPrefs(viewPrefs);
        pVisAids.loadPrefs(viewPrefs);
    }

    public void storePrefs(Preferences viewPrefs) {
        pBaseCarto.storePrefs(viewPrefs);
        pVisAids.storePrefs(viewPrefs);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pSurfShpLayers = new net.falappa.wwind.widgets.SurfShapeLayersVisibilityPanel();
        pVisAids = new net.falappa.wwind.widgets.VisualAidsVisibilityPanel();
        pBaseCarto = new net.falappa.wwind.widgets.BaseCartoVisibilityPanel();

        setTitle("Layer settings");
        setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pSurfShpLayers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pVisAids, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pBaseCarto, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSurfShpLayers, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pBaseCarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pVisAids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.falappa.wwind.widgets.BaseCartoVisibilityPanel pBaseCarto;
    private net.falappa.wwind.widgets.SurfShapeLayersVisibilityPanel pSurfShpLayers;
    private net.falappa.wwind.widgets.VisualAidsVisibilityPanel pVisAids;
    // End of variables declaration//GEN-END:variables
}
