/*
 * Copyright 2014 Alessandro Falappa <alex.falappa@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gui.panels;

import gui.CapabilitiesWorker;
import java.awt.Dimension;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.falappa.swing.table.StringListTableModel;
import net.opengis.www.cat.wrs._1_0.CatalogueStub;

/**
 *
 * @author Alessandro Falappa <alex.falappa@gmail.com>
 */
public class CollectionsPanel extends javax.swing.JPanel {

    private final StringListTableModel ctm = new StringListTableModel();
    private CatalogueStub stub = null;

    public CollectionsPanel() {
        initComponents();
        tblColls.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                bDel.setEnabled(tblColls.getSelectedRow() >= 0);
            }
        });
        // hack to preserve the space between the list and the panel border when the buttons are made invisible
        // the code below sets the filler width to the GroupLayout container gap according to the current Look&Feel
        Dimension dim = new Dimension(javax.swing.LayoutStyle.getInstance().getContainerGap(filler1, SwingConstants.EAST, this), 10);
        filler1.setPreferredSize(dim);
        filler1.setMaximumSize(dim);
        filler1.setMinimumSize(dim);
    }

    public boolean isCollectionSelected() {
        return tblColls.getSelectedRowCount() > 0;
    }

    public void setButtonsVisible(boolean visible) {
        bAdd.setVisible(visible);
        bDel.setVisible(visible);
        bDiscover.setVisible(visible);
        ctm.setEditable(visible);
    }

    public boolean isButtonsVisible() {
        return bAdd.isVisible();
    }

    public String[] getSelectedCollections() {
        String[] ret = null;
        final int numSelRows = tblColls.getSelectedRowCount();
        if (numSelRows > 0) {
            ret = new String[numSelRows];
            int[] selRows = tblColls.getSelectedRows();
            for (int idx = 0; idx < selRows.length; idx++) {
                ret[idx] = (String) ctm.getValueAt(selRows[idx], 0);
            }
        }
        return ret;
    }

    public String[] getCollections() {
        String[] ret = new String[ctm.getRowCount()];
        for (int i = 0; i < ret.length; i++) {
            ret[i] = (String) ctm.getValueAt(i, 0);
        }
        return ret;
    }

    public void setCollections(String[] collections) {
        ctm.clear();
        for (String c : collections) {
            ctm.addString(c);
        }
    }

    public void setStub(CatalogueStub stub) {
        this.stub = stub;
        bDiscover.setEnabled(true);
    }

    public void removeStub() {
        this.stub = null;
        bDiscover.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bAdd = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblColls = new javax.swing.JTable();
        bDiscover = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(12, 0), new java.awt.Dimension(12, 0), new java.awt.Dimension(12, 32767));

        jLabel1.setText("Collections");

        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images_16x16/glyphicons_432_plus.png"))); // NOI18N
        bAdd.setToolTipText("Add collection name");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images_16x16/glyphicons_433_minus.png"))); // NOI18N
        bDel.setToolTipText("Remove selected collection name");
        bDel.setEnabled(false);
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });

        tblColls.setModel(ctm);
        tblColls.setFillsViewportHeight(true);
        tblColls.setShowHorizontalLines(false);
        tblColls.setShowVerticalLines(false);
        tblColls.setTableHeader(null);
        jScrollPane2.setViewportView(tblColls);

        bDiscover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images_16x16/glyphicons_194_circle_question_mark.png"))); // NOI18N
        bDiscover.setToolTipText("Discovery collections trough GetCapabilities");
        bDiscover.setEnabled(false);
        bDiscover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDiscoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(bAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDiscover)))
                .addGap(0, 0, 0)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bAdd)
                        .addComponent(bDel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(bDiscover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        ctm.addString("collection");
        tblColls.scrollRectToVisible(tblColls.getCellRect(ctm.getRowCount() - 1, 0, true));
    }//GEN-LAST:event_bAddActionPerformed

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        final int selectedRow = tblColls.getSelectedRow();
        if (selectedRow >= 0) {
            ctm.removeString(selectedRow);
        }
    }//GEN-LAST:event_bDelActionPerformed

    private void bDiscoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDiscoverActionPerformed
        CapabilitiesWorker worker = new CapabilitiesWorker(stub, this);
        worker.execute();
    }//GEN-LAST:event_bDiscoverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bDiscover;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblColls;
    // End of variables declaration//GEN-END:variables
}
