/*
 * Copyright 2014 Alessandro Falappa <alex.falappa@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gui.panels;

import gui.dialogs.XmlDialog;
import main.App;

/**
 *
 * @author Alessandro Falappa <alex.falappa@gmail.com>
 */
public class SearchButtonsPanel extends javax.swing.JPanel {

    private XmlDialog xd;

    public SearchButtonsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spMaxRecs = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spStartPos = new javax.swing.JSpinner();
        bHits = new javax.swing.JButton();
        bResults = new javax.swing.JButton();
        bShowReq = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbDetail = new javax.swing.JComboBox();

        jLabel1.setText("Max");

        spMaxRecs.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(100), Integer.valueOf(1), null, Integer.valueOf(5)));

        jLabel2.setText("records from");

        spStartPos.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(5)));

        bHits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images_16x16/glyphicons_027_search_number.png"))); // NOI18N
        bHits.setText("Hits");
        bHits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitsActionPerformed(evt);
            }
        });

        bResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images_16x16/glyphicons_027_search.png"))); // NOI18N
        bResults.setText("Results");
        bResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResultsActionPerformed(evt);
            }
        });

        bShowReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images_16x16/glyphicons_359_file_export.png"))); // NOI18N
        bShowReq.setToolTipText("Show current request");
        bShowReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowReqActionPerformed(evt);
            }
        });

        jLabel3.setText("Detail");

        cbDetail.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brief", "Summary", "Full" }));
        cbDetail.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spMaxRecs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spStartPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bShowReq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bResults)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bHits)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {spMaxRecs, spStartPos});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bHits, bResults});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spMaxRecs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spStartPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bHits)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bShowReq, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bResults)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bHitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitsActionPerformed
        App.frame.execHits();
    }//GEN-LAST:event_bHitsActionPerformed

    private void bResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResultsActionPerformed
        App.frame.execResults();
    }//GEN-LAST:event_bResultsActionPerformed

    private void bShowReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowReqActionPerformed
        String reqText = App.frame.getReqText();
        if (reqText != null) {
            if (xd == null) {
                xd = new XmlDialog(App.frame);
            }
            xd.setSourceText(reqText);
            xd.setLocationRelativeTo(App.frame);
            xd.setVisible(true);
        }
    }//GEN-LAST:event_bShowReqActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHits;
    private javax.swing.JButton bResults;
    private javax.swing.JButton bShowReq;
    private javax.swing.JComboBox cbDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spMaxRecs;
    private javax.swing.JSpinner spStartPos;
    // End of variables declaration//GEN-END:variables

    public void enableButtons(boolean enabled) {
        bHits.setEnabled(enabled);
        bResults.setEnabled(enabled);
    }

    public int getStartPos() {
        return (int) spStartPos.getValue();
    }

    public int getMaxRecs() {
        return (int) spMaxRecs.getValue();
    }

    public int getDetail() {
        return cbDetail.getSelectedIndex();
    }
}
